### PR TITLE
Update for Factorio Version 0.17.0

### PR DESCRIPTION
**Pull request by JDOGG88**

### CODE REVIEW

**Comment by kendfrey** [comment]
Do you mind putting the mod files back in src? It is intentionally there to separate the mod code from the other parts of the repo.

Thanks for taking the time to do this. I appreciate it!

**Comment by JDOGG88** [comment]
With it like that factorio doesn't seem to recognize the mod, which is why I changed it to reflect the base game file structure.  I really like it separated but I don't know if they did something with 0.17 that disallows it. :(

You're welcome, I love this mod and also used your tinting code for my own Void Works mod ^_^

**Comment by kendfrey** [comment]
When you say it doesn't seem to recognize it, have you been copying the whole repository into the mods  folder, or just the contents of the src folder? I haven't tried it in 0.17 yet, but 0.16 needs the src folder only (renamed to the correct name).

**Comment by JDOGG88** [comment]
Oooooooooo, okay that makes way more sense hahaha.  I misunderstood what you were trying to accomplish and only have it for the repo and not the mod itself.  My apologies and yes I can totally change it back then.  Give me a few minutes here and I'll push it.

**Comment by JDOGG88** [comment]
Done ^_^

**Comment by kendfrey** [comment]
Thanks so much, I'll try to test it out in a bit.

**Comment by JDOGG88** [comment]
Awesome! I tested it myself and it works for me at least with the mods I use which are all bobs mods.  So I'm assuming it should work for anyone haha.  Thank you for making an amazing mod to begin with.

**Comment by kendfrey** [comment]
Tested and published. Excellent work!

**Comment by JDOGG88** [comment]
Awesome glad I could help ^_^

**Pull request merged**
